// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasePanel: typeof import('./settings/components/BasePanel.vue')['default']
    Button: typeof import('primevue/button')['default']
    CandidatesView: typeof import('./candidates/views/CandidatesView.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    EmployeesView: typeof import('./employees/views/EmployeesView.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    HomeView: typeof import('./home/views/HomeView.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiInput: typeof import('./shared/components/MultiInput.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ProjectsView: typeof import('./projects/views/ProjectsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./settings/views/SettingsView.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TheCreateEmployeeDialog: typeof import('./employees/components/TheCreateEmployeeDialog.vue')['default']
    TheProfilePanel: typeof import('./settings/components/TheProfilePanel.vue')['default']
    VacanciesView: typeof import('./vacancies/views/VacanciesView.vue')['default']
    VacancyView: typeof import('./vacancies/views/VacancyView.vue')['default']
  }
}
