// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasePanel: typeof import('./settings/components/BasePanel.vue')['default']
    BubbleHint: typeof import('./settings/components/BubbleHint.vue')['default']
    Button: typeof import('primevue/button')['default']
    EmployeesView: typeof import('./employees/views/EmployeesView.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    HomeView: typeof import('./home/views/HomeView.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ProjectsView: typeof import('./projects/views/ProjectsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./settings/views/SettingsView.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TheNotificationPanel: typeof import('./settings/components/TheNotificationPanel.vue')['default']
    TheProfilePanel: typeof import('./settings/components/TheProfilePanel.vue')['default']
  }
}
