// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    EmployeesView: typeof import('./employees/views/EmployeesView.vue')['default']
    HomeView: typeof import('./home/views/HomeView.vue')['default']
    ProjectsView: typeof import('./projects/views/ProjectsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./settings/views/SettingsView.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
